const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{早餐選擇哪個比較低碳: 0},
	{早餐選擇_哪個比較低碳___2_removebgpreview: 0},
	{蛋餅豆漿: 0},
	{三明治奶茶: 0},
	{沙拉罐裝飲料: 0},
	{早餐選擇哪個比較低碳2: 0},
	{進入碳選擇: 0},
	{滑鼠: 0},
	{精靈: 0},
	{精靈2: 0},
	{精靈3: 0},
	{前一頁: 0},
	{下一頁: 0},
	{早餐選擇哪個比較低碳3: 0},
	{腳踏車: 0},
	{公車: 0},
	{捷運: 0},
	{早餐選擇哪個比較低碳4: 0},
	{音頻: 0},
	{早餐選擇哪個比較低碳5: 0},
	{換個選擇: 0},
	{早餐選擇哪個比較低碳6: 0},
	{早餐選擇哪個比較低碳7: 0},
	{早餐選擇哪個比較低碳8: 0},
	{早餐選擇哪個比較低碳9: 0},
	{繼續: 0},
	{早餐選擇哪個比較低碳10: 0},
	{早餐選擇哪個比較低碳11: 0},
	{冷氣電風: 0},
	{電燈電視: 0},
	{筆電手機: 0},
	{精靈4: 0},
	{精靈5: 0},
	{精靈6: 0},
	{早餐選擇哪個比較低碳12: 0}
];

self.InstanceType = {
	早餐選擇哪個比較低碳: class extends self.ISpriteInstance {},
	早餐選擇_哪個比較低碳___2_removebgpreview: class extends self.ISpriteInstance {},
	蛋餅豆漿: class extends self.ISpriteInstance {},
	三明治奶茶: class extends self.ISpriteInstance {},
	沙拉罐裝飲料: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳2: class extends self.ISpriteInstance {},
	進入碳選擇: class extends self.ISpriteInstance {},
	滑鼠: class extends self.IInstance {},
	精靈: class extends self.ISpriteInstance {},
	精靈2: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	前一頁: class extends self.ISpriteInstance {},
	下一頁: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳3: class extends self.ISpriteInstance {},
	腳踏車: class extends self.ISpriteInstance {},
	公車: class extends self.ISpriteInstance {},
	捷運: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳4: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	早餐選擇哪個比較低碳5: class extends self.ISpriteInstance {},
	換個選擇: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳6: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳7: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳8: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳9: class extends self.ISpriteInstance {},
	繼續: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳10: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳11: class extends self.ISpriteInstance {},
	冷氣電風: class extends self.ISpriteInstance {},
	電燈電視: class extends self.ISpriteInstance {},
	筆電手機: class extends self.ISpriteInstance {},
	精靈4: class extends self.ISpriteInstance {},
	精靈5: class extends self.ISpriteInstance {},
	精靈6: class extends self.ISpriteInstance {},
	早餐選擇哪個比較低碳12: class extends self.ISpriteInstance {}
}